[build]
kill_delay = "10s"
delay = 500
include_dir = []
exclude_dir = ["public", "tmp", "vendor", "node_modules"]
include_ext = ["go", "tpl", "tmpl", "html", "templ", "css", "sql"]
exclude_regex = ["_test.go", ".*_templ.go"]


[proxy]
enabled = true
proxy_port = 3001
app_port = 3000

